### ISSUE TITLE
Pymongo support

### ISSUE THREAD

**Issue by docapotamus** [opbeat/opbeat_python#108]
In the Opbeat performance metrics I can not see any calls made to MongoDB.

I am willing to add this myself via a PR. Does this require anything on the server side? Or just an update on the client?

Thanks

**Comment by piquadrat** [comment]
Hey @docapotamus. Sorry for the delay. Adding support for MongoDB shouldn't require any server-side changes. In fact, our module for node.js already has support for MongoDB: https://github.com/opbeat/opbeat-node/blob/master/lib/instrumentation/modules/mongodb-core.js

A PR would be fantastic! You can get some hints how our instrumentation works by looking at the existing modules that we instrument: https://github.com/opbeat/opbeat_python/tree/master/opbeat/instrumentation/packages

**Comment by piquadrat** [comment]
@docapotamus we implemented PyMongo support in #132 and will cut a release soon. If you have some time, we'd be thrilled if you could give it a go!

Closing this ticket in the meantime.
