### ISSUE TITLE
"library frames"

### ISSUE THREAD

**Issue by dwieeb** [opbeat/opbeat_python#112]
Opbeat is pretty good at hiding the library frames for Flask, newrelic, librato, std library, etc. We wrap Flask in our own Python package (installed separately, so think of it as third party) such that every single one of our reported errors have a stack trace that ends with the same three calls (our error handling and reporting code).

Is there a way to tell Opbeat to treat a certain Python package as just another library and have those stack frames collapsed by default?

**Comment by piquadrat** [comment]
Unfortunately, it is currently not possible to influence the in-app detection. However, as far as I understand you, you install your custom package just as any other package, so our detection should theoretically be able to figure it out. Can you send us an example of an error to support@opbeat.com?
