### ISSUE TITLE
Test and check commands do not work with Django 1.10

### ISSUE THREAD

**Issue by pixerius** [opbeat/opbeat_python#122]
```
./manage.py opbeat test
usage: manage.py opbeat [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                        [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                        [-o ORGANIZATION_ID] [-a APP_ID] [-t SECRET_TOKEN]
manage.py opbeat: error: unrecognized arguments: test
```

`test` and `check` commands are not recognized as arguments in django 1.10.

**Comment by piquadrat** [comment]
@pixerius thanks for the report. We're working on support for Django 1.10 and will release an update soon

**Comment by piquadrat** [comment]
@pixerius we just uploaded version 3.4 of the Opbeat module to pypi, with support for Django 1.10. Can you give it a try?

**Comment by pixerius** [comment]
@piquadrat works as expected. thanks!

**Comment by piquadrat** [comment]
Great, thanks for checking!
