### ISSUE TITLE
Missing errors (unable to validate data)

### ISSUE THREAD

**Issue by OmegaDroid** [opbeat/opbeat_python#130]
I have setup opbeat on my django project. When I run `manage.py opbeat test` everything works fine and I see the test error in my opbeat dashboard. When my site raises a `FileNotFoundError` error from template rendering however I see nothing.

I have dug into the request being sent and the response is:
```
{
    "status": 400, 
    "error_message": "Unable to validate data.", 
    "structured_error": {
        "template": {
            "context_line": "None is not of type <class \\'str\\'>"
        }
    }
}
```

This doesn't seem to happen with all errors however, `DisallowedHost` errors are being reported fine.

**Comment by roncohen** [comment]
Hi @OmegaDroid.

Thanks for reaching out and sorry for the slow reply.
We have just deployed a fix for a related error. Could you check if you're still experiencing this?

**Comment by OmegaDroid** [comment]
Hi @roncohen, that seems to be working now thanks :+1:

**Comment by roncohen** [comment]
Wonderful. Feel free to reopen if this happens again.
