### ISSUE TITLE
400 error opbeat http transport "SERVER_PORT": "80 is not of type <class \'str\'>"

### ISSUE THREAD

**Issue by txels** [opbeat/opbeat_python#131]
We get the following error when opbeat tries to report an exception from our django service (django 1.10, python 3.5). Our error happens when an HTTP request to another service fails. Then opbeat tries to report the error and fails to do so.

Looks like the issue is internal to the opbeat client (we use 3.2.1).

```
Failed to submit message: "ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /files/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object a..."
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/opbeat/transport/http.py", line 41, in send
    response = urlopen(req, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/opbeat/transport/http.py", line 90, in send_sync
    url = HTTPTransport.send(self, data, headers)
  File "/usr/local/lib/python3.5/dist-packages/opbeat/transport/http.py", line 63, in send
    raise TransportException(message, data, print_trace=print_trace)
opbeat.transport.base.TransportException: Unable to reach Opbeat server: HTTP Error 400: Bad Request (url: https://intake.opbeat.com/api/v1/organizations/505f5950e52e4b049acce63db8fe85ab/apps/750d8b0cb1/errors/, body: b'{\n    "error_message": "Unable to validate data.", \n    "structured_error": {\n        "http": {\n            "env": {\n                "SERVER_PORT": "80 is not of type <class \'str\'>"\n            }\n        }\n    }, \n    "status": 400\n}')
```

We'll try to upgrade to latest version while we don't hear back from you guys on this issue.

**Comment by txels** [comment]
Upgrading to 3.4.0 does not fix this issue.

**Comment by txels** [comment]
After doing some internal debugging, I realised that in python 3.5.1, django 1.10.1 (I haven't checked other combinations), `request.META['SERVER_PORT']` is an int and not a str:

```python
ipdb> request.META['SERVER_PORT']
7000
```

This appears to be in contradiction with the django docs (https://docs.djangoproject.com/en/1.10/ref/request-response/#django.http.HttpRequest.META) that state:

> SERVER_PORT – The port of the server (as a string).

So I'd say this looks like it may be a bug/backwards-incompatible change in Django or python (DJango probably .

Maybe, to be on the defensive side, the opbeat server should accept integer values for `SERVER_PORT` if they are valid port numbers.

**Comment by txels** [comment]
Hmm, I think this is caused by django channels. It uses its own ASGI request and sets SERVER_PORT, as an integer:

https://github.com/django/channels/blob/master/channels/handler.py#L68

**Comment by piquadrat** [comment]
Thanks for the report @txels. Thanks for the thorough investigation. We should be able to implement a workaround for this server-side. I'll let you know when this is shipped.

**Comment by piquadrat** [comment]
@txels we just shipped a workaround. Can you check from your side if errors get through our validation again?

**Comment by txels** [comment]
This worked well, thanks!

**Comment by piquadrat** [comment]
Great, thanks again for the report!
