### ISSUE TITLE
Template rendering broken with Django 1.9 ?

### ISSUE THREAD

**Issue by nMustaki** [opbeat/opbeat_python#133]
Hi,

we tried Opbeat on our test server, which is in debug mode but it crashed template rendering.

Running python manage.py opbeat check is working, performances and errors are sent to Obpeat, but the middleware breaks template rendering with error TypeError: object.__init__() takes no parameters

It breaks line 113 of opbeat/contrib/django/middleware/__init__.py
```python
def __init__(self, *args, **kwargs):
    super(OpbeatAPMMiddleware, self).__init__(*args, **kwargs)
    self.client = get_client()
```

The stacktrace of the processors list shows the Opbeat middleware being a class while others are functions : 
```python
(<function csrf at 0x7fa24ba24398>,
 <class 'opbeat.contrib.django.middleware.OpbeatAPMMiddleware'>,
 <function auth at 0x7fa24ba24848>,
 <function request at 0x7fa24ba24668>,
 <function debug at 0x7fa24ba24410>,
 <function i18n at 0x7fa24ba24488>,
 <function media at 0x7fa24ba245f0>,
 <function static at 0x7fa24ba24578>,
 <function messages at 0x7fa24ba24f50>)
```
I tried to have the middleware inherit from object, but I got others errors, so I gave up.
Opbeat 3.3.3 is also not working.

Do you have pointers on this one ?

Thanks you !

**Comment by andres-torres-marroquin** [comment]
My guess is that you're misconfiguring your settings.py. I'm currently using django 1.9, without problems. I think you're setting up a Middleware in the template context processors. The `'opbeat.contrib.django.middleware.OpbeatAPMMiddleware'`, goes in `MIDDLEWARE_CLASSES`

**Comment by nMustaki** [comment]
Many thanks !
