### ISSUE TITLE
Support for new MIDDLEWARE in Django 1.10

### ISSUE THREAD

**Issue by apollo13** [opbeat/opbeat_python#147]
It would be nice if the middlewares also supported the new middlewares in 1.10 which guarantee that the response path is always called, basically you'd need to add a `__call__` and modify `__init__` but could then dispatch to the existing methods.

**Comment by piquadrat** [comment]
@apollo13 sorry for the long response time, Christmas break got in the way a bit.

As for new style middlewares, I was assuming that inheriting from `django.utils.deprecation.MiddlewareMixin` would automatically handle this. Isn't that enough?

**Comment by apollo13** [comment]
@piquadrat Oh, I was looking at the WSGI middleware, sorry. Gotta see what my initial error was -- will reopen if I find something.
