### ISSUE TITLE
Connection pool drop for almost every request

### ISSUE THREAD

**Issue by babu-upcomer** [opbeat/opbeat_python#149]
```
DEBUG 2017-01-06 07:20:48,682 connectionpool 20960 139981346472016 Resetting dropped connection: intake.opbeat.com
DEBUG 2017-01-06 07:20:48,727 connectionpool 20960 139981346472016 https://intake.opbeat.com:443 "POST /api/v1/organizations/<xxxxxx>/apps/<xxxxxx>/transactions/ HTTP/1.1" 202 61
```

Lately, we'are receiving this debug logs for almost every request to our backend. We have configured the performance middleware along with the default settings in the docs.

**Comment by beniwohli** [comment]
Hi @babu-upcomer. Sorry for the long wait on this :(

This debug message is nothing to be concerned about. The TCP connection is only kept open for a few seconds, and transactions are sent every minute or so.
