### ISSUE TITLE
py36: exception on import six: AttributeError: 'NoneType' object has no attribute 'submodule_search_locations'

### ISSUE THREAD

**Issue by a-sonets** [opbeat/opbeat_python#162]
Global __spec__ is None when try to import Opbeat on initializing pytest tests (Flask).

Possible fix:
  ```
if globals().get("__spec__") is not None:
     __spec__.submodule_search_locations = []  # PEP 451 @UndefinedVariable
```

**Comment by beniwohli** [comment]
@a-sonets thanks for the report, and sorry for the long silence here. It looks like this is an issue in the `six` library which we vendor, and has been fixed in a newer version. Vendoring a newer version of the library should help. I'll try to get a fix out this week.
