### ISSUE TITLE
Django 1.11 support?

### ISSUE THREAD

**Issue by brylie** [opbeat/opbeat_python#183]
The Cookiecutter Django project depends on this package. Currently, Cookiecutter Django is pinned to Django 1.10.x, based on an [issue to check for 1.11.x support in project dependencies](https://github.com/pydanny/cookiecutter-django/issues/1111). 

Is the opbeat_python package known to work with Django 1.11?

**Comment by beniwohli** [comment]
Hi @brylie. We run our [test suite](https://travis-ci.org/opbeat/opbeat_python) with Django 1.11, and have lots of customers running the Opbeat module on Django 1.11

**Comment by brylie** [comment]
Thanks for the confirmation. I will quote your reply in the downstream issue.
