### ISSUE TITLE
psycopg2.sql – SQL string composition (psycopg2 2.7+) breaks opbeat

### ISSUE THREAD

**Issue by nicoknoll** [opbeat/opbeat_python#196]
Hey, after upgrading to psycopg2 2.7 I started to use the SQL string composition (see first line of the traceback) which seems to break the opbeat "extract_signature" function. Here is the traceback:

```
Traceback (most recent call last):
...
cur.execute(select_sql.format(sql.Identifier(table_name)))
File "/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
return self.cursor.execute(sql)
File "/venv/lib/python3.6/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 169, in execute
return self._trace_sql(self.__wrapped__.execute, sql, params)
File "/venv/lib/python3.6/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 176, in _trace_sql
signature = self.extract_signature(sql)
File "/venv/lib/python3.6/site-packages/opbeat/instrumentation/packages/psycopg2.py", line 13, in extract_signature
return extract_signature(sql)
File "/venv/lib/python3.6/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 126, in extract_signature
sql = sql.strip()
AttributeError: 'Composed' object has no attribute 'strip'
```

You can reproduce it by simply trying to call cursor.execute on and sql composition (like in the first line of the traceback).

Is there a way to disable opbeat for some specific cursor.execute calls or do you already have this issue on your list and we just have to update opbeat?

Thanks,
Nico

**Comment by beniwohli** [comment]
Hi Nico!

Thanks for the report, we will look into it. I wasn't aware of this new feature in psycopg2. 

Unfortunately, there is no good way to disable opbeat only for certain queries, so you'll probably have to disable Opbeat completely for now. I hope to have a fix for this soon.

**Comment by beniwohli** [comment]
@nicoknoll correction, you can disable instrumentation of psychopg2 by setting the environment variable `SKIP_INSTRUMENT_PSYCOPG2` to a non-empty value

**Comment by nicoknoll** [comment]
Thanks for the fast reply :) Probably going with `SKIP_INSTRUMENT_PSYCOPG2` for now then but obviously we'd rather continue monitoring sql with opbeat :)

Btw.: I think it should be really easy to fix this - just need to check if sql is "Composed" and if so call "as_string" (http://initd.org/psycopg/docs/sql.html#psycopg2.sql.Composable.as_string) on it before continuing.

**Comment by beniwohli** [comment]
Yup, that's what it looks like. Unfortunately, `as_string()` also needs a cursor or connection, which we haven't needed there so far, so this also needs a bit of refactoring :)

**Comment by nicoknoll** [comment]
@beniwohli Thanks a lot!

**Comment by beniwohli** [comment]
@nicoknoll I didn't manage to push the release to PyPI just yet, but I will tomorrow

BTW, as you might know, Opbeat joined with @elastic last year, and we're working on bringing the Opbeat experience to the Elastic Stack. We have a [beta release](https://www.elastic.co/blog/elastic-apm-beta-released) out, would be awesome to hear what you think.

The Python Opbeat agent will only see sporadic fixes over the next few months until we sunset Opbeat.com on May 24
