### ISSUE TITLE
ImportError: No module named http

### ISSUE THREAD

**Issue by koalalorenzo** [opbeat/opbeat_python#27]
When using opbeat 2.0.1 I have this error on my testing machine. By installing the 2.0.0 version it is working perfectly. This is the error generated by pytest

```python
/usr/local/lib/python2.7/dist-packages/opbeat/__init__.py:20: in <module>
    from opbeat.base import *
/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:159: in load_module
    py.builtin.exec_(co, mod.__dict__)
/usr/local/lib/python2.7/dist-packages/opbeat/base.py:41: in <module>
    from opbeat.transport.http import HTTPTransport, AsyncHTTPTransport
E   ImportError: No module named http
```

Is this my fault?

**Comment by roncohen** [comment]
Hey @koalalorenzo. We've been unable to reproduce this. Is is still a problem?

**Comment by koalalorenzo** [comment]
Yes, basically we are stuck to version 2.0.0 because the 2.0.1 is not working for us. I also tried to create from scratch a docker container to test this and the problem was there. Could it be a problem caused by opbeatcli? it is raised only when I use pytest.

**Comment by roncohen** [comment]
It could very well be the opbeat-cli. We've deprecated the opbeat-cli in favour of a simple CURL call. Try to unstall the opbeat-cli and take a look here: https://opbeat.com/docs/articles/get-started-with-release-tracking/

**Comment by koalalorenzo** [comment]
Even if I switched to curl, the problem is still there. We are keeping 2.0.0, but I promise that I will test once in a while.

**Comment by roncohen** [comment]
@koalalorenzo Hey! A lot has happened in the module since you last tried it. Can you give it another try?

**Comment by koalalorenzo** [comment]
Sadly I am not working anymore with opbeat, and I don't have access to the server. You may contact minbildinbil.dk support to get in touch with the Tech Guy... but I remember that they planned to take the website down, so I don't know if they are still using it, so they can test. Sorry!

**Comment by roncohen** [comment]
Very sad to hear it @koalalorenzo. I'll try to reach out to them.
