### ISSUE TITLE
With persistent connections, opbeat can cause an additional error when collecting user data

### ISSUE THREAD

**Issue by roncohen** [opbeat/opbeat_python#50]
With Django's persistent connections, it can happen that a connection to the database is closed for misc. reasons. This will cause an `OperationalError` in Django. When Opbeat tries to pick up the user information for that error, it tries accessing the database, causing an additional `OperationalError`.

Solution for now is to catch any `OperationalError`s when we're gathering the extra data (user info etc.) and not bubble it up further. It would be nice if we instead added a note to the data that we were unable to collect it before it's sent.

cc @apollo13

**Comment by apollo13** [comment]
FWIW, this can also happen without persistent connections -- but it is easier to see and reproduce if you have persistent connections.
