### ISSUE TITLE
Django 404 middleware does not respect settings.DEBUG

### ISSUE THREAD

**Issue by RasmusKlett** [opbeat/opbeat_python#81]
The Django middleware "opbeat.contrib.django.middleware.OpbeatAPMMiddleware" does not send errors when settings.DEBUG = False. 
I would expect the same behaviour from "opbeat.contrib.django.middleware.Opbeat404CatchMiddleware", but it is not the case. From skimming the code, it does not appear that it attempts to check DEBUG at all, so it is probably just a matter of making it use the same check as the APMMiddleware.

**Comment by piquadrat** [comment]
Thanks for the report @RasmusKlett, that's absolutely correct. I just merged a fix, it will be shipped with the next version of the module.

In the meantime, you can make Opbeat not send any data (e.g. during tests) by setting the `OPBEAT_DISABLE_SEND` environment variable to `true`.

**Comment by RasmusKlett** [comment]
Great news.
In the meantime I just conditionally add the middleware based on the value of DEBUG, works like a charm :)
