### ISSUE TITLE
Opbeat appears to still be attempting to send, when explicitly disabled

### ISSUE THREAD

**Issue by tarkatronic** [opbeat/opbeat_python#82]
Here's what I'm seeing; I think it is pretty self explanatory:

```
$ OPBEAT_DISABLE_SEND=true ./manage.py test --keepdb
Using existing test database for alias 'default'...
...................................................
----------------------------------------------------------------------
Ran 51 tests in 2.227s

OK
Preserving test database for alias 'default'...
PID 74871: Opbeat is attempting to send 1 pending messages
Waiting up to 10 seconds, press Ctrl-C to quit
PID 74871: done, took 0.21 seconds to complete

$ pip freeze | grep opbeat
opbeat==3.1.3

$ ./manage.py shell
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
...
>>> pprint.pprint(settings.OPBEAT)
{'APP_ID': 'xxxx',
 'DEBUG': True,
 'ORGANIZATION_ID': 'xxxxx',
 'SECRET_TOKEN': 'xxxxx'}
```

Should I still be seeing these messages, and just trust that nothing is being sent?

**Comment by piquadrat** [comment]
@tarkatronic that's odd. Thanks for reporting, we'll investigate!

**Comment by piquadrat** [comment]
@tarkatronic I'm not able to replicate this :( Can you verify that the version of Opbeat that is used by Django is really 3.1.3, e.g. with this command?

    echo "import opbeat; print(opbeat.VERSION)" | ./manage.py shell

**Comment by tarkatronic** [comment]
```
$ echo "import opbeat; print(opbeat.VERSION)" | ./manage.py shell
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 3.1.3
>>>
```

**Comment by tarkatronic** [comment]
Crap, looks like this was my bad. I was referencing my own checkout of opbeat_python, rather than the one in site-packages. Sorry about that. Strange that it still reported a version of 3.1.3 though, when my fork is 3.1.1. Perhaps a strange bug in the version reporting?

**Comment by piquadrat** [comment]
The version issue might stem from this code: https://github.com/opbeat/opbeat_python/blob/a72e4e69e23deefbcc4be3cc281b3a089f1c0b60/opbeat/__init__.py#L15-L16
