### ISSUE TITLE
Django 1.9 crash

### ISSUE THREAD

**Issue by jbub** [opbeat/opbeat_python#88]
Dont know why, but client sometimes crashes on Django 1.9 with:

`'NoneType' object has no attribute 'lineno' `

**Crashes on this line**
https://github.com/opbeat/opbeat_python/blob/master/opbeat/contrib/django/utils.py#L98

**Setup**
Django==1.9.1
opbeat==3.1.3

Maybe `renderer.token` can be `None` in some cases ?

**Comment by piquadrat** [comment]
Thanks for the report @jbub! We're working on a fix already. We're still trying to understand under which circumstances the `renderer` (which is a `Node` instance) doesn't have a valid token at the moment. I hope to have the fix out soon.

**Comment by jbub** [comment]
If its helps, in my case renderer contains:
`'<Block Node: javascript. Contents: [<TextNode: u\'\\n    \'>, <Variable Node: block.super>, <TextNode: u\'\\n    <script src="https:/\'>]>'`

Seems like it is crashing when rendering `pipeline.templatetags.pipeline.render_js` template tag. https://github.com/jazzband/django-pipeline/blob/master/pipeline/templatetags/pipeline.py#L113

**Comment by piquadrat** [comment]
@jbub we just released version 3.1.4 of the agent, which should hopefully fix this. I wasn't able to reproduce the issue myself, could you give it a try with your project?

**Comment by jbub** [comment]
@piquadrat Thanks, im on it.

**Comment by piquadrat** [comment]
Awesome, thanks for the update @jbub!

**Comment by piquadrat** [comment]
Fixed in #89 / 3.1.4. Feel free to re-open if the error reappears :)

**Comment by jbub** [comment]
Okay, thanks, will report here if something fails.
