### ISSUE TITLE
The requests instrumentation swallows exceptions

### ISSUE THREAD

**Issue by gcbirzan** [opbeat/opbeat_python#95]
If you try to use it with a malformed URL (no schema) the exception becomes:

opbeat/instrumentation/packages/requests.py", line 29, in call
    signature += " " + host
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by roncohen** [comment]
Hi @gcbirzan,

Thank you for the bug report. Much appreciated. I'll take a look.

**Comment by jalvz** [comment]
Hi @gcbirzan ,

This issue is fixed now in the last version (3.2.2)

Thanks!
